version: "3.7"
services:

  app:
    build:
      args:
        # get your user and uid from system
        user: ${USER}
        uid: ${UID:-1000}
      context: .
      dockerfile: ./Dockerfile
    container_name: 'app'
    image: laravel-pm-app:latest
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - proxynet

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./docker/nginx/log:/var/log/nginx
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8020:80"
    networks:
      - proxynet

  db:
    image: mariadb:10.5.9
    container_name: 'db'
    restart: unless-stopped
    ports:
      - '8040:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
      MYSQL_DATABASE: 'homestead'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - proxynet

  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    depends_on:
      - db
    environment:
      ADMINER_DESIGN: nette
      ADMINER_PLUGINS: tables-filter tinymce
    ports:
      - 8030:8080
    networks:
      - proxynet

volumes:
  db_data:


networks:
  proxynet:
    name: mynet
